### ISSUE TITLE
[request] few icons missing

### ISSUE THREAD

**Issue by ahjolinna** [MichaelTiebesl/Plat#2]
I use chakraOS/KDE so there are few things missing,

distro/KDE:
spectacle (replaces KSnapshot), [KDE-Services](https://www.kde-look.org/content/show.php/KDE-Services?content=147065), kcm-pacman-repoeditor (icon name is: database-chakra)

Apps: 
[YACReader](http://www.yacreader.com/), [franz](http://meetfranz.com/), [Vivaldi](https://vivaldi.com/?lang=en), [bomi](http://bomi-player.github.io/), [makemkv](http://www.makemkv.com/), [mkv-extractor-qt5](https://www.linux-apps.com/p/1131021/), [obs](https://obsproject.com/), [SVP4](https://www.svp-team.com/wiki/Main_Page), [vokoscreen](https://github.com/vkohaupt/vokoscreen), [t-lasku](http://helineva.net/t-lasku/), [googleplaydownloader](https://codingteam.net/project/googleplaydownloader)

I dont think there isnt any point with (steam)games

**Comment by MichaelTiebesl** [comment]
At this moment i don't have that much time to work on icons request. I just started with this icon theme. I had it before with material colors and with a long shadow accent. I'm now removing the long shadow accent and also change the colors to make it better looking. This will take some weeks for me. After that i can work on your request. Hopefully you understand.

**Comment by ahjolinna** [comment]
np there is no hurry with these, it's nice to hear that your are doing more work for this theme.
